---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (RedHat)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist 
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages for RedHat servers
    tags: apache,apache2,redhat
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat"

  - name: install apache and php packages for Ubuntu servers
    tags: apache,ubuntu,apach2
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (RedHat)
    tags: mariadb,redhat
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "RedHat"

  - name: install mariadb package (Ubuntu)
    tags: mariadb,ubuntu
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: innstall samba package
    tags: samba
    package:
      name: samba
      state: latest
